--Generated with Kogitsune's Resource Generator
resource.AddFile( "HUD/armor.png" )
resource.AddFile( "HUD/check.png" )
resource.AddFile( "HUD/close.png" )
resource.AddFile( "HUD/craft.png" )
resource.AddFile( "HUD/exam.png" )
resource.AddFile( "HUD/gmTrash.png" )
resource.AddFile( "HUD/health.png" )
resource.AddFile( "HUD/skills.png" )
resource.AddFile( "HUD/xmark.png" )
resource.AddFile( "SKILLS/agility.png" )
resource.AddFile( "SKILLS/arms.png" )
resource.AddFile( "SKILLS/crafting.png" )
resource.AddFile( "SKILLS/endurance.png" )
resource.AddFile( "SKILLS/leadership.png" )
resource.AddFile( "SKILLS/stealth.png" )
resource.AddFile( "SKILLS/survival.png" )
resource.AddFile( "SKILLS/vehicles.png" )
resource.AddFile( "PDA/inventory.png")
resource.AddFile( "PDA/settings.png")
resource.AddFile( "PDA/quests.png")
resource.AddFile( "PDA/factions.png")
resource.AddFile( "PDA/close.png")
resource.AddFile( "PDA/map.png")
resource.AddFile( "PDA/skills.png")
resource.AddFile( "PDA/locked.png")
resource.AddFile( "PDA/unlocked.png")
resource.AddFile( "PDA/perk.png")
resource.AddFile( "EDITOR/minus.png")
resource.AddFile( "EDITOR/clockwise.png")
resource.AddFile( "EDITOR/counterclock.png")